server:
  port: 7001
  servlet:
    context-path: /ad-serach
spring:
  application:
    name: eureka-client-ad-search
  datasource:
    hikari:
      username: yuwen
      password: lyp82nlf
      maximum-pool-size: 10
      minimum-idle: 3
      connection-timeout: 30000
      connection-test-query: select 1
      pool-name: hikari-pool
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ad_data?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 5
        max-wait: 6000
    timeout: 1000

eureka:
  client:
    service-url:
      defaultZone: http://local.eureka.server:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"                #暴露全部信息
logging:
  level:
    top.ezttf.ad: debug


adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: yuwen
    password: lyp82nlf
    binlogName:
    position: -1

  kafka:
    topic: ad-search-mysql-data