spring:
  application:
    name: eureka-client-ad-gateway

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://local.eureka.server:8000/eureka/
zuul:
  prefix: /my-zuul
  routes:
    sponsor:
      # **为通配符(任意字符,支持多级目录), ?(任意单个字符), *(任意字符,支持一级目录)
      path: /ad-sponsor/**
      service-id: eureka-client-ad-sponsor
      # 设置不跳过前缀
      strip-prefix: false
    search:
      path: /ad-search/**
      serviceId: eureka-client-ad-search
      strip-prefix: false
logging:
  level:
    top.ezttf.ad: debug