spring:
  application:
    name: ad-gateway

server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://local.eureka.server:8000/eureka/

zuul:
  prefix: /zuul
  routes:
    sponsor:
      path: /ad-sponsor/**        # **为通配符(任意字符,支持多级目录), ?(任意单个字符), *(任意字符,支持一级目录)
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false         # 设置不跳过前缀
