spring:
  application:
    name: ad-dump
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ad_data?autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ad-dump-hikari-pool
      username: yuwen
      password: lyp82nlf
      maximum-pool-size: 5
      minimum-idle: 1
      max-lifetime: 28800
      connection-timeout: 30000
      auto-commit: true
      connection-test-query: select 1
server:
  port: 9999
  servlet:
    context-path: /ad-dump

eureka:
  client:
    service-url:
      defaultZone: http://local.eureka.server:8000/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"                #暴露全部信息

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
    default-statement-timeout: 30000
  type-aliases-package: top.ezttf.ad.pojo

logging:
  level:
    top.ezttf.ad: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  row-bounds-with-count: false
